### ISSUE TITLE
Write a Fenwick Tree in Java

### ISSUE THREAD

**Issue by imaprincess** [imaprincess/Algorithms-4-everyone#1]
Write a Fenwick Tree in Java
Rules:
- The code must be full of comments (we have to understand what the code is doing!) 
- The code must be in the Graph Teory & Trees > Fenwick Tree and named FenwickTree.java 
- Use as few classes as possible 
- Your code must be clear - please don't use little known functionalities! 

Thanks 🦄

**Comment by Cosmopal** [comment]
I can work on it, pls assign it to me :) @imaprincess

**Comment by Cosmopal** [comment]
Please merge the pull request. If possible please assign this issue first :)
