### ISSUE TITLE
Write Sort Algorithms in Java

### ISSUE THREAD

**Issue by imaprincess** [imaprincess/Algorithms-4-everyone#2]
Rules:
- The code must be full of comments (we have to understand what the code is doing!) 
- The code must be in the Sort Algorithms > Java 
- Your code must be clear - please don't use little known functionalities! 

Thanks 🦄

**Comment by imaprincess** [comment]
I'm sorry, I think that someone has already begun writing it :( 
I'm opening other issues, what programming languages do you know? I can assign you to write these algorithms, but in another language if you want ❤️

**Comment by imaprincess** [comment]
Look at the issues! :)

**Comment by afilini** [comment]
I'm actually working on the Java implementation of some sorting algorithms, as you can see here: https://github.com/afilini/Algorithms-4-everyone/tree/java_sort_algo
