### ISSUE TITLE
Write sort algorithms in Python

### ISSUE THREAD

**Issue by imaprincess** [imaprincess/Algorithms-4-everyone#3]
Rules:

The code must be full of comments (we have to understand what the code is doing!)
The code must be in the Sort Algorithms > Python
Your code must be clear - please don't use little known functionalities!
Thanks 🦄

**Comment by i-Gagan** [comment]
Well i Would Really prefer This one too !

**Comment by imaprincess** [comment]
Okey, as I've written in the last issue, I'll assign you asap

**Comment by i-Gagan** [comment]
Done !

**Comment by imaprincess** [comment]
Perfect, make the pull request! I think you can do it even if I haven't assigned you to this issue, am I wrong? :(

**Comment by i-Gagan** [comment]
I can't ! now , you have to assign me first for me to make submission .

**Comment by imaprincess** [comment]
I'm sorry for this, I am having little issues, but maybe you can help me:
when I click assign, the only person I can assign this issue to is myself and I don't know what to do :c 
Otherwise, someone has just made a pull request - are you sure that you can't? 
If you go to https://github.com/imaprincess/Algorithms-4-everyone/pulls , don't you have a green button "new pull request"?

**Comment by malikshubham827** [comment]
@i-Gagan You can send a PR without being assigned. 

@imaprincess As far as I know to be assigned the [other person must be a collaborator.](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/)

**Comment by imaprincess** [comment]
Thanks 💋 

(I'd prefer to not add collaborators, I'm sorry lol, you'll have to do the pr without assignments)

**Comment by malikshubham827** [comment]
@imaprincess Do you want some Graph Algorithms apart from sort. I have some.

**Comment by imaprincess** [comment]
@malikshubham827 yes thanks! 
You can create new folders in Graph Theory & Trees, the name of the folder must be the name of the algorithm obviously :) Then, in the folder create files like nameofthealgorithm.py :)

**Comment by vaibhavsingh97** [comment]
@imaprincess Added selection sort in python. More sorting algorithm coming soon 😄

**Comment by i-Gagan** [comment]
`` #Added BubbleSort in python.

**Comment by i-Gagan** [comment]
@imaprincess Added Bubble Sort Algorithm!

**Comment by dzarrini** [comment]
I would like to be add as well if possible?

**Comment by imaprincess** [comment]
@dzarrini as you can see, we've got BubbleSort, InsertionSort and SelectionSort. You can write other algorithms: mergeSort, shellSort, radixSort, quickSort... 😍

**Comment by DrunkenLord** [comment]
@imaprincess I have added Python code for merge sort and added the extension .py to bubble sort.
More Algorithms coming soon!
