### ISSUE TITLE
Trie

### ISSUE THREAD

**Issue by AkshGautam** [imaprincess/Algorithms-4-everyone#33]
Added trie in Cpp.Please review PR #22

**Comment by imaprincess** [comment]
Please delete Fenwick.py, otherwise I can't merge the pull request :c

**Comment by AkshGautam** [comment]
@imaprincess  ok i'll do that

**Comment by AkshGautam** [comment]
@imaprincess  would you please label this issue as hacktoberfest so other interested people can contribute more.Thanks

**Comment by AkshGautam** [comment]
Please review PR #22 .i have made the changes @imaprincess

**Comment by visage98** [comment]
There is no code for Trie in java.
Should i add it?
@imaprincess

**Comment by imaprincess** [comment]
Yes please c: @visage98

**Comment by visage98** [comment]
@imaprincess Added PR #40 .
Please check.

**Comment by Mansi-Mittal** [comment]
is a code for trie in java merged?
