### ISSUE TITLE
No tree algorithm in Javascript

### ISSUE THREAD

**Issue by MadhavBahlMD** [imaprincess/Algorithms-4-everyone#39]

**Comment by MadhavBahlMD** [comment]
@imaprincess should i add Tree programs in JS?

**Comment by imaprincess** [comment]
Sure c:

**Comment by MadhavBahlMD** [comment]
Ok i will start my work tomorro.
Can you plz add hacktoberfest label 😄

**Comment by MadhavBahlMD** [comment]
@imaprincess Just added script for tree implementation in Javascript using objects 👍
