### ISSUE TITLE
Write sort algorithms in JS 

### ISSUE THREAD

**Issue by imaprincess** [imaprincess/Algorithms-4-everyone#4]
Rules:

The code must be full of comments (we have to understand what the code is doing!)
The code must be in the Sort Algorithms > JavaScript 
Your code must be clear - please don't use little known functionalities!
Thanks 🦄

**Comment by i-Gagan** [comment]
Now You Can assign Me to This Task !!

**Comment by imaprincess** [comment]
I'm having some troubles, I can't assign you :c 
Start writing the code, I'll assign you asap

**Comment by cynthiajbuck** [comment]
I do not see a JavaScript folder within the Sort Algorithms folder. If I make a pull request, do I make a JavaScript folder to put it in?

**Comment by imaprincess** [comment]
Exactly!

**Comment by rjp84** [comment]
What are you trying to sort? I have a sql background and am new to JavaScript so I typically only use common functions.

**Comment by MadhavBahlMD** [comment]
OK i will help! 
Will do some sorting algorithms in Javascript!

**Comment by MadhavBahlMD** [comment]
@imaprincess can i take pigeonhole sort in Javascript?

**Comment by imaprincess** [comment]
@MadhavBahlMD sure :)

**Comment by MadhavBahlMD** [comment]
Awesome 😃 
I would love to contribute 👍  and keep good comments inside my code.
