### ISSUE TITLE
Dynamic Programming c:

### ISSUE THREAD

**Issue by imaprincess** [imaprincess/Algorithms-4-everyone#44]
I'd like to improve the repo by adding some dp famous problems.
Can someone help me?
You can do problem as knapsack problem, longest increasing sequence or other well known problems.
The code must be full of comments (we have to understand what the code is doing!)
The code must be in Dynamic Programming, you have to create a folder named as the algorithm you're creating
Your code must be clear - please don't use little known functionalities!
You can write in C/C++, Java, JS, Python
Thanks 🦄

**Comment by tanya-vedi** [comment]
I can contribute in Java and C++.

**Comment by codyalgorith** [comment]
i can help with cpp code.

**Comment by codyalgorith** [comment]
I have submitted two solutions for DP problems ,but sadly ,you havent merged them nor you have provided any feedback to improve them. help will be appreciated.

**Comment by jenish9599** [comment]
I would like to contribute in java.

**Comment by jenish9599** [comment]
I have added  Largest_Increasing_Subsequence.
Review PR #64.

**Comment by adikul30** [comment]
Have a look at #65
