### ISSUE TITLE
Write a Fenwick Tree in Python

### ISSUE THREAD

**Issue by imaprincess** [imaprincess/Algorithms-4-everyone#5]
Rules:

- The code must be full of comments (we have to understand what the code is doing!)
- The code must be in the Graph Teory & Trees > Fenwick Tree and named FenwickTree.py
- Your code must be clear - please don't use little known functionalities!
Thanks 🦄

**Comment by AkshGautam** [comment]
Can I be assigned for this issue?

**Comment by AkshGautam** [comment]
Created a PR for the issue.Please review.Any suggestion is welcom!.Thanks
