### ISSUE TITLE
Refractor Codes.

### ISSUE THREAD

**Issue by khokharnikunj8** [imaprincess/Algorithms-4-everyone#69]
@imaprincess  @jenish9599 @vaibhavsingh97 Codes are being randomly added in the repo . please refractor it according to Their types.

i.e Disjoint Set , Fenwick Tree , Trie should be in the Advanced data structure section . 
there should be different sections for algorithm and data structures.

**Comment by imaprincess** [comment]
You're right, but in this period I haven't got enough time to help improving this repo
I am very sad, I noticed it and I'd be very grateful if someone helped me reorganising the code c:

**Comment by khokharnikunj8** [comment]
@imaprincess  should I help on this issue?

**Comment by imaprincess** [comment]
@khokharnikunj8 you seem well organised, so, if you want, sure you can help ☺️

**Comment by vaibhavsingh97** [comment]
@khokharnikunj8 I can help too 😄

**Comment by khokharnikunj8** [comment]
@vaibhavsingh97 I already finished it.
