### ISSUE TITLE
Java 8 implementation of Histogram Equalization Algorithm

### ISSUE THREAD

**Issue by vn17** [imaprincess/Algorithms-4-everyone#70]

**Comment by vn17** [comment]
Please add the hacktoberfest label

**Comment by TheGamer007** [comment]
I'm interested in implementing this. I'm thinking of putting the code in a new folder `Image Processing Algorithms` under `/Algorithms/`. The Readme mentioned that the rules to be followed would be mentioned in the respective issue, but there's nothing here?

**Comment by vn17** [comment]
Hi @TheGamer007. I have already implemented this in pull request #76 . I had created this PR for myself. It would be nice if you can implement some other Image Processing Algorithm and put it under `Image Processing Algorithms`
